name: Deploy Node Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Log in to docker hub
        run:  docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"


      - name: Build Docker Image
        run: docker build -t devbyvishnu/forever_fullstack_ecom .

      - name: Publish Image to docker hub
        run: docker push devbyvishnu/forever_fullstack_ecom:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull devbyvishnu/forever_fullstack_ecom:latest

      - name: Run Docker Container
        run: |
            docker run -d -p 4000:4000 --name forever_fullstack_ecom-container \
              -e MONGO_PASSWORD='${{ secrets.MONGO_PASSWORD }}' \
              -e JWT_SECRET='${{ secrets.JWT_SECRET }}' \
              -e ADMIN_EMAIL='${{ secrets.ADMIN_EMAIL }}' \
              -e ADMIN_PASSWORD='${{ secrets.ADMIN_PASSWORD }}' \
              -e MONGODB_URI='${{ secrets.MONGODB_URI }}' \
              -e CLOUDINARY_API_KEY='${{ secrets.CLOUDINARY_API_KEY }}' \
              -e CLOUDINARY_SECRET_KEY='${{ secrets.CLOUDINARY_SECRET_KEY }}' \
              -e CLOUDINARY_NAME='${{ secrets.CLOUDINARY_NAME }}' \
              -e RAZORPAY_KEY_SECRET='${{ secrets.RAZORPAY_KEY_SECRET }}' \
              -e RAZORPAY_KEY_ID='${{ secrets.RAZORPAY_KEY_ID }}' \
              devbyvishnu/forever_fullstack_ecom:latest

